### ISSUE TITLE
Facing issue 

### ISSUE THREAD

**Issue by manoj29076** [fhh200000/HACKINTOSH-MSI-B550M-PRO-VDH-WIFI#1]
Hello fhh200000,

My system cinfig is:
- ADM AMD Ryzen 5 5600X Processor 
- MSI b550m pro-vdh wifi Motherboard 
- ASUSTek NVIDIA GeForce GTX 1650 
- 16GB RAM 
- 
I am trying to install macOS using code "HACKINTOSH-MSI-B550M-PRO-VDH-WIFI", and there is showing error "00:000 00:000 OC: Driver OpenRuntime.efi at 0 cannot be loaded - Access Denied!" 

After OC validating found errors (attached) 
![error](https://github.com/fhh200000/HACKINTOSH-MSI-B550M-PRO-VDH-WIFI/assets/142295793/035cebb3-7a5b-4e1e-908b-463120de2029)
Need help to install macOS on my PC.
Thank you
Manoj Kumar

**Comment by fhh200000** [comment]
> Hello fhh200000,
> 
> My system cinfig is:
> 
>     * ADM AMD Ryzen 5 5600X Processor
> 
>     * MSI b550m pro-vdh wifi Motherboard
> 
>     * ASUSTek NVIDIA GeForce GTX 1650
> 
>     * 16GB RAM
> 
> 
> I am trying to install macOS using code "HACKINTOSH-MSI-B550M-PRO-VDH-WIFI", and there is showing error "00:000 00:000 OC: Driver OpenRuntime.efi at 0 cannot be loaded - Access Denied!"
> 
> After OC validating found errors (attached) ![error](https://user-images.githubusercontent.com/142295793/260649270-035cebb3-7a5b-4e1e-908b-463120de2029.jpg) Need help to install macOS on my PC. Thank you Manoj Kumar

Hi Manoj,

The OpenCore boot loader do not have backward/forward compat. That is, if you want to use my OpenCore configuration, you may only use the version in the repo. If you want to upgrade, you may need to write from scratch.

Hope this information helps!

Igniculus

**Comment by manoj29076** [comment]
Thank you for the reply, I am not a tech person. Can you please guide me how I can Install MacOS on my PC. I already shared my PC configuration in my previous communication.

Thanks you.
Manoj

**Comment by fhh200000** [comment]
> Thank you for the reply, I am not a tech person. Can you please guide me how I can Install MacOS on my PC. I already shared my PC configuration in my previous communication.
> 
> Thanks you. Manoj

Hi Manoj,

Your ASUSTek NVIDIA GeForce GTX 1650 is not compatible with ANY version of MacOS, so you can only change a graphic card.
Besides this, you need to do the followings:

1. Clone this repo.
2. Use _macserial_ tool from official OpenCore repo to generate system IDs for your own. 
3. Copy all files to your ESP partition (i.e., EFI System Partition), or to a FAT32 USB flash disk temporarily if you want a quick test.
4. Reboot, and boot from a entry named "UEFI OS" or "Opencore".

Hope that helps!

Igniculus

**Comment by manoj29076** [comment]
Thank you so much. your are helpful.

Thanks again.
Manoj
